version: "3"

env:
  THEME: loveit
tasks:
  grab-theme:
    desc: Install theme
    cmds:
      - git clone https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng
      - cp index.html themes/hello-friend-ng/layouts/
      - mkdir -p themes/hello-friend-ng/layouts/_default/_markup/
      - cp render-codeblock-mermaid.html themes/hello-friend-ng/layouts/_default/_markup/render-codeblock-mermaid.html
      - cat mermaid >> themes/hello-friend-ng/layouts/partials/javascript.html
      - cp javascript.html themes/hello-friend-ng/layouts/partials/javascript.html
    silent: true

  test:
    desc: Test site locally
    cmds:
      - hugo server -t $THEME
    silent: true

  deploy:
    desc: Deploy site
    cmds:
      - ./scripts/deploy-sftp.sh
    silent: true

  build:
    desc: Build the site
    cmds:
      - hugo -t $THEME
    silent: true
