name: Gitea Actions Hugo Build
run-name: Testing hugo 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Checkout theme repo
        uses: actions/checkout@v3
        with:
          repository: dillonzq/LoveIt
          path: themes/LoveIt
          github-server-url: https://github.com/
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: Build
        run: hugo --minify
