name: Gitea Actions Hugo Build
run-name: Testing hugo 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
